### ISSUE TITLE
cannot compote

### ISSUE THREAD

**Issue by gstormlee** [rekby/etcddir#4]
package github.com/coreos/etcd/mvcc/mvccpb: cannot find package "github.com/coreos/etcd/mvcc/mvccpb" in any of:
	/usr/local/Cellar/go/1.10/libexec/src/github.com/coreos/etcd/mvcc/mvccpb (from $GOROOT)
	/Users/wmli/go/src/github.com/coreos/etcd/mvcc/mvccpb (from $GOPATH)
wmli in ~/go/src/github.com λ

**Comment by rekby** [comment]
Thanks
Fixed
